---
apiVersion: v1
kind: Service
metadata:
  name: easy-email-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: easy-email
